language: node_js
node_js:
- node
install:
- npm install
script:
- npm run build || true
deploy:
  skip_cleanup: true
  provider: npm
  email: taoabc@gmail.com
  api_key:
    secure: kxqAjBd7rUuAwTFLoUggt6O/4ASV1cP3tJROk8EuBOr135DVdsdUIA4b8z+9ywFdo2FMwnP6iWWhGQ7z+oWAOIl2UVye8YEmUkoe6c4iXvMmzt5WscWR7SRFKlk+4sf9gTHKLVGc/RUEOqpiiESZz2DFoR4Q29IKMlBUxFPiCrprICPqNcf6DvduWrGJOmxITwLg4ZFcPm74vFBhH+8/3HsN8OOYyWaNUWO23+rBIs6Zig3T78p7HLeSqsRBjVs+Ht7a1mp1wZIb+tmVZtLZnMZjV5D5NBlKHiCN6dPKHC44CD9UW3FsTPdad0QZdhXPD7XKvq8tKM2Pcy6s5k3qzt2X5ab+Bcn4GRF2H5I5ahC2vpJtDd7nsu1h2IpSOKQvrMOvH3MHfshuPlY2SJCCIgUPp0+yhQ3HHrJee6ACPY1KQBzB9S2F7YsYQTxYBcA9L3ZQIUywQ5sJoDYwJ60w5/n4IQG6slMxVgsuW4DS8NoDuO68laEQrU5M7PXsvnxc6vs3XEIvGTgWnaSCAFHIbuspmgEHqLamldwxDTKWvuP14Ojh2vZC6A5s/R2XIE9QC4+B++lmh5VY2dib23iomVuV0fFRDO+jH6LufoiFsv9XF02mcsrzHobLwFA9fTdxxdKk1vn0n7LBSs3UDtRl0kFzvekJik4XozkmlyHAF8Y=
  on:
    repo: taoabc/libdragonbones
    tags: true
    all_branches: true
